# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "taxonRank", # <add_row_server>
  "taxonomicStatus", # <autocomplete_server>
  "scientificName", # <autocomplete_server>
  "taxonRank", # <autocomplete_app>
  "taxonRank", # <modify_row_server>
  NULL
))
