# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "taxonRank", # <add_row_server>
  "taxonomicStatus", # <autocomplete_server>
  "scientificName", # <autocomplete_server>
  "taxonRank", # <autocomplete_app>
  "scientificName", # <fetch_single_parent>
  "parentNameUsageID", # <fetch_single_parent>
  "taxonID", # <fetch_parents>
  "scientificName", # <fetch_synonyms>
  "taxonID", # <fetch_synonyms>
  "scientificName", # <fetch_children_one_level_single>
  "taxonID", # <fetch_children_one_level_single>
  "taxonomicStatus", # <fetch_children>
  "scientificName", # <fetch_children>
  "taxonID", # <fetch_children>
  "scientificName", # <subset_to_taxon_single>
  "taxonID", # <subset_to_taxon_single>
  "value", # <make_empty_ppg>
  "name", # <summarize_branches>
  "branch", # <summarize_branches>
  "session_title", # <summarize_branches>
  "session_summary", # <summarize_branches>
  "scientificName", # <submit_changes>
  "taxonID", # <submit_changes>
  "taxonRank", # <modify_row_server>
  "taxonRank", # <subset_server>
  "scientificName", # <subset_server>
  NULL
))
